version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - godot
    - bodyclose
    - err113
    - errorlint
    - revive
    - sqlclosecheck
    - unparam
    - importas
    - gosec

run:
  go: '1.23'

skip-files:
  - ^skip_me\.go$
  

